"""add_lat_lng_to_shipments

Revision ID: 10ffd10f495f
Revises: 4ca3cd04bcb5
Create Date: 2026-09-11 00:25:32.026960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ffd10f495f'
down_revision: Union[str, None] = '4ca3cd04bcb5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shipments', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('shipments', sa.Column('current_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shipments', 'current_lng')
    op.drop_column('shipments', 'current_lat')
    # ### end Alembic commands ###
