"""add_lat_lng_to_shipments

Revision ID: 4ca3cd04bcb5
Revises: bdfbc26d48c1
Create Date: 2026-09-10 23:55:03.532716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca3cd04bcb5'
down_revision: Union[str, None] = 'bdfbc26d48c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('current_lat', sa.Float(), nullable=True))
    op.add_column('vehicles', sa.Column('current_lng', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'current_lng')
    op.drop_column('vehicles', 'current_lat')
    # ### end Alembic commands ###
